//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KFCEntities : DbContext
    {
        public KFCEntities()
            : base("name=KFCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payment_Methods> Payment_Methods { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSelling> ProductSelling { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<View_Payment_Methods> View_Payment_Methods { get; set; }
        public virtual DbSet<View_Orders> View_Orders { get; set; }
        public virtual DbSet<View_Products> View_Products { get; set; }
        public virtual DbSet<View_ProductSelling> View_ProductSelling { get; set; }
    }
}
