//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProductSelling = new HashSet<ProductSelling>();
        }
    
        public int ID_Order { get; set; }
        public Nullable<int> Payment_Method_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.TimeSpan> Order_Time { get; set; }
    
        public virtual Payment_Methods Payment_Methods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSelling> ProductSelling { get; set; }
    }
}
