//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPrimary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XPrimaryEntities : DbContext
    {
        public XPrimaryEntities()
            : base("name=XPrimaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payment_Methods> Payment_Methods { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSelling> ProductSelling { get; set; }
        public virtual DbSet<vw_Orders> vw_Orders { get; set; }
        public virtual DbSet<vw_Payment_Methods> vw_Payment_Methods { get; set; }
        public virtual DbSet<vw_Products> vw_Products { get; set; }
        public virtual DbSet<vw_ProductSelling> vw_ProductSelling { get; set; }
    }
}
