//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPrimary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Orders
    {
        public int ID_Order { get; set; }
        public Nullable<int> Payment_Method_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.TimeSpan> Order_Time { get; set; }
    }
}
