//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPrimary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Products
    {
        public int ID_Product { get; set; }
        public string Product_Name { get; set; }
        public int Amount_In_Storage { get; set; }
        public int Price { get; set; }
    }
}
