//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPrimary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Payment_Methods
    {
        public int ID_Payment_Method { get; set; }
        public string Payment_Type { get; set; }
    }
}
